### ISSUE TITLE
Publish the generator

### ISSUE THREAD

**Issue by Buslowicz** [mlisook/generator-polymer-init-twc-element#3]
Hey ;). Would you mind publishing this generator to NPM? It works pretty good and I've already been asked for a working sample code (which could be provided from your generator). I would then close the draccoz/twc#101 :).

**Comment by mlisook** [comment]
Thanks for the nudge.  I've published this on NPM - [registry page](https://www.npmjs.com/package/generator-polymer-init-twc-element).

I'm also working on 2 generators.  One a bare bones app, the other the PRPL pattern PWA template.  Just need a little free time to wrap them up.

**Comment by Buslowicz** [comment]
Sounds really great! Can't wait to see them :D.
Anyway, thanks for publishing, and for the generator itself ;).
